/**
 * Generates everything font-related from src/lib/templates/fonts.json:
 *
 *   public/fonts/*.woff2                          the files themselves
 *   src/lib/templates/generated/unicode-ranges.json  which glyphs each covers
 *   src/app/fonts.css                             the browser's @font-face rules
 *
 * All three are derived, all three are gitignored, and this runs on postinstall,
 * predev and prebuild so they are always present before anything reads them.
 *
 * Why copy out of node_modules at all: the PDF renderer needs to read these
 * files at runtime by a computed path, and Turbopack cannot resolve a specifier
 * it is unable to see through. A directory of static assets sidesteps the
 * bundler completely, and has the bonus that the browser and the renderer are
 * demonstrably loading the same bytes.
 *
 * Safe to run repeatedly — files already present at the right size are skipped.
 */

import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const require = createRequire(import.meta.url);
const root = path.resolve(import.meta.dirname, "..");
const fontDir = path.join(root, "public", "fonts");
const generatedDir = path.join(root, "src", "lib", "templates", "generated");
const cssFile = path.join(root, "src", "app", "fonts.css");

const manifest = JSON.parse(
  fs.readFileSync(path.join(root, "src", "lib", "templates", "fonts.json"), "utf8"),
);

/** Mirrors fontFileName() in src/lib/templates/fonts.ts. */
const fileName = (font, subset, weight) => `${font.slug}-${subset}-${weight}-normal.woff2`;

function packageDir(pkg) {
  // Resolving package.json rather than the package root: fontsource sets
  // "exports", which makes the root itself unresolvable from Node.
  return path.dirname(require.resolve(`${pkg}/package.json`));
}

const BANNER = "/* Generated by scripts/sync-fonts.mjs. Do not edit. */";

function main() {
  fs.mkdirSync(fontDir, { recursive: true });
  fs.mkdirSync(generatedDir, { recursive: true });

  const wanted = new Set();
  const missing = [];
  const ranges = {};
  const faces = [];
  let copied = 0;

  for (const font of manifest.fonts) {
    const dir = packageDir(font.pkg);

    // Each package ships the exact unicode-range Google split the subsets on.
    // Taking it from the package rather than hardcoding it means a font update
    // that reshuffles coverage is picked up instead of silently disagreeing.
    const unicode = JSON.parse(fs.readFileSync(path.join(dir, "unicode.json"), "utf8"));
    ranges[font.slug] = {};

    for (const subset of font.subsets) {
      // A range is only meaningful when a family is split across several files
      // and the browser has to choose between them. Single-subset families such
      // as DejaVu Sans ship an empty unicode.json and want no range at all —
      // declaring one would exclude every glyph outside it.
      const range = unicode[subset] ?? null;
      if (range === null && font.subsets.length > 1) {
        missing.push(`${font.family}: no unicode range published for subset "${subset}"`);
        continue;
      }
      if (range !== null) ranges[font.slug][subset] = range;

      for (const weight of font.weights) {
        const name = fileName(font, subset, weight);
        wanted.add(name);

        const from = path.join(dir, "files", name);
        const to = path.join(fontDir, name);

        if (!fs.existsSync(from)) {
          missing.push(`${font.family}: ${path.relative(root, from)} does not exist`);
          continue;
        }

        const src = fs.statSync(from);
        const dst = fs.statSync(to, { throwIfNoEntry: false });
        if (!dst || dst.size !== src.size) {
          fs.copyFileSync(from, to);
          copied += 1;
        }

        // font-display: block — the browser must never paint a fallback, even
        // for a frame, or the measurement the auto-fit takes is of the wrong
        // font. The server's rules are built the same way in font-embed.ts.
        faces.push(
          `@font-face {\n` +
            `  font-family: "${font.family}";\n` +
            `  font-style: normal;\n` +
            `  font-weight: ${weight};\n` +
            `  font-display: block;\n` +
            `  src: url("/fonts/${name}") format("woff2");\n` +
            (range === null ? "" : `  unicode-range: ${range};\n`) +
            `}`,
        );
      }
    }
  }

  if (missing.length > 0) {
    console.error("sync-fonts: fonts.json does not match what is installed:");
    for (const line of missing) console.error(`  ${line}`);
    process.exit(1);
  }

  // A font dropped from the manifest must stop being served, or a stale file
  // keeps a removed family working locally and it breaks on a clean checkout.
  let removed = 0;
  for (const name of fs.readdirSync(fontDir)) {
    if (name.endsWith(".woff2") && !wanted.has(name)) {
      fs.unlinkSync(path.join(fontDir, name));
      removed += 1;
    }
  }

  writeIfChanged(
    path.join(generatedDir, "unicode-ranges.json"),
    `${JSON.stringify(ranges, null, 2)}\n`,
  );
  writeIfChanged(
    cssFile,
    `${BANNER}\n/* Subsets and ranges here are identical to those embedded in the PDF. */\n\n${faces.join("\n\n")}\n`,
  );

  const parts = [`${wanted.size} files current`];
  if (copied > 0) parts.push(`${copied} copied`);
  if (removed > 0) parts.push(`${removed} stale removed`);
  console.log(`sync-fonts: ${parts.join(", ")}`);
}

function writeIfChanged(file, contents) {
  // Rewriting an unchanged file would retrigger the dev server's watcher on
  // every predev, which turns `npm run dev` into a reload loop.
  let existing = null;
  try {
    existing = fs.readFileSync(file, "utf8");
  } catch {
    // Not written yet.
  }
  if (existing !== contents) fs.writeFileSync(file, contents);
}

main();
