import { existsSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { allFontFiles, BUNDLED_FONTS, findFont, fontFileName, stack } from "@/lib/templates/fonts";
import ranges from "@/lib/templates/generated/unicode-ranges.json";
import { familiesFor, TYPE_PAIRINGS } from "@/lib/templates/tokens";

/**
 * The fit guarantee rests on the browser and the PDF renderer loading exactly
 * the same font files. These tests pin that down, because the failure mode is
 * silent: nothing throws, the PDF just quietly gets set in a different font and
 * runs onto a second page.
 *
 * public/fonts, the range map and fonts.css are all generated by
 * scripts/sync-fonts.mjs, which `pretest` runs. Asserting on the output rather
 * than the script is deliberate — it is the output both runtimes consume.
 */

const root = path.join(import.meta.dirname, "..", "..");
const fontDir = path.join(root, "public", "fonts");
const fontsCss = readFileSync(path.join(root, "src", "app", "fonts.css"), "utf8");

const rangeMap = ranges as Record<string, Record<string, string> | undefined>;

describe("bundled fonts", () => {
  it("ships every file it claims to", () => {
    for (const { font, subset, weight } of allFontFiles()) {
      const name = fontFileName(font, subset, weight);
      const file = path.join(fontDir, name);
      expect(existsSync(file), `${font.family}: ${name} missing from public/fonts`).toBe(true);
      expect(statSync(file).size, name).toBeGreaterThan(0);
    }
  });

  it("serves the browser the same files the PDF embeds", () => {
    // Same filenames on both sides means the same bytes: the renderer reads
    // public/fonts directly and the browser fetches it over /fonts.
    for (const { font, subset, weight } of allFontFiles()) {
      const name = fontFileName(font, subset, weight);
      expect(fontsCss, `${font.family} ${subset} ${weight}`).toContain(`url("/fonts/${name}")`);
    }
  });

  it("does not serve the browser a file the PDF cannot embed", () => {
    const declared = new Set(
      allFontFiles().map(({ font, subset, weight }) => fontFileName(font, subset, weight)),
    );
    const referenced = [...fontsCss.matchAll(/url\("\/fonts\/([^"]+)"\)/g)].map((m) => m[1]);

    expect(referenced.length).toBe(declared.size);
    for (const name of referenced) {
      expect(declared.has(name), `${name} is served but not declared`).toBe(true);
    }
  });

  it("splits multi-subset families on a published unicode range", () => {
    // Without a range the browser uses the first matching @font-face and
    // ignores the rest, so every accented character would silently fall back
    // to a system font while the PDF rendered it correctly, or vice versa.
    for (const font of BUNDLED_FONTS) {
      if (font.subsets.length < 2) continue;
      for (const subset of font.subsets) {
        const range = rangeMap[font.slug]?.[subset];
        expect(range, `${font.family} ${subset}`).toBeTruthy();
        expect(fontsCss, `${font.family} ${subset}`).toContain(`unicode-range: ${range};`);
      }
    }
  });

  it("leaves single-subset families unrestricted", () => {
    // DejaVu Sans is one file covering everything it has; a range could only
    // exclude glyphs it actually contains.
    for (const font of BUNDLED_FONTS) {
      if (font.subsets.length > 1) continue;
      expect(rangeMap[font.slug] ?? {}, font.family).toEqual({});
    }
  });

  it("covers accented European names, which is the realistic ceiling", () => {
    // "Å" (U+00C5) and "ż" (U+017C) between them exercise both subsets.
    const latin = rangeMap.carlito?.latin ?? "";
    const latinExt = rangeMap.carlito?.["latin-ext"] ?? "";
    expect(latin).toContain("U+0000-00FF");
    expect(latinExt).toContain("U+0100-02BA");
  });

  it("ships a bold weight for every family, since headings are bold", () => {
    for (const font of BUNDLED_FONTS) {
      expect(font.weights, font.family).toContain(700);
    }
  });

  it("records a redistributable licence for every family", () => {
    for (const font of BUNDLED_FONTS) {
      expect(font.licence, font.family).toMatch(/OFL|Apache|Bitstream/);
    }
  });
});

describe("type pairings", () => {
  it("only reference families that are bundled", () => {
    for (const pairing of TYPE_PAIRINGS) {
      for (const family of familiesFor(pairing.id)) {
        expect(findFont(family), `${pairing.id} uses unbundled ${family}`).toBeDefined();
      }
    }
  });

  it("put the bundled family first in the stack", () => {
    for (const pairing of TYPE_PAIRINGS) {
      const css = stack(pairing.bodyFamily, pairing.generic);
      expect(css.startsWith(`"${pairing.bodyFamily}"`), css).toBe(true);
    }
  });

  it("end every stack in a generic family", () => {
    for (const pairing of TYPE_PAIRINGS) {
      const css = stack(pairing.bodyFamily, pairing.generic);
      expect(css.endsWith("serif") || css.endsWith("sans-serif"), css).toBe(true);
    }
  });

  it("names the metric-compatible original where there is one", () => {
    // A reader recognises "Calibri", not "Carlito". The note has to say so.
    const carlito = TYPE_PAIRINGS.find((t) => t.id === "carlito");
    expect(carlito?.note).toContain("Calibri");
  });
});
